name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect "XPlat Code coverage"
    - name: Report
      run: | 
        dotnet tool install -g dotnet-reportgenerator-globaltool
        reportgenerator -reports:$GITHUB_WORKSPACE/**/coverage.cobertura.xml -targetdir:$GITHUB_WORKSPACE/CodeCoverage -reporttypes:'HtmlInline'
    - name: Upload coverage report
      uses: actions/upload-artifact@v2.3.0
      with:
        name: code-coverage-report
        path: $GITHUB_WORKSPACE/CodeCoverage/
